# Generated by Django 3.2.4 on 2023-04-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
