# Generated by Django 3.2.4 on 2023-04-21 02:09

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_login_require'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/', validators=[blog.models.Post.validate_image]),
        ),
    ]
