# Generated by Django 3.2.4 on 2023-04-21 02:20

import blog.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='handout',
            field=blog.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
