# Generated by Django 3.2.4 on 2023-04-21 02:22

import blog.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_handout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='handout',
            field=blog.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/', verbose_name='Media'),
        ),
    ]
