# Generated by Django 3.2.4 on 2023-04-21 02:50

import blog.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_handout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='handout',
        ),
        migrations.AddField(
            model_name='post',
            name='audio',
            field=blog.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/', verbose_name='audio'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=blog.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/', verbose_name='video'),
        ),
    ]
